# Generated by Django 2.2 on 2020-04-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0004_auto_20200421_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='タグ')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='relation',
            field=models.ManyToManyField(blank=True, null=True, related_name='_post_relation_+', to='postapp.Post', verbose_name='関連'),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='postapp.Tag', verbose_name='タグ'),
        ),
    ]
