# Generated by Django 2.2 on 2020-04-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200416_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proftext',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='プロフィール'),
        ),
    ]
