version: '3.7'

services:
    django:
        # Dockerfileを探す
        build: 
            # 読み込むファイル名が`Dockerfile`ではない場合contextに相対パス、dockerfileにファイル名を記載
            context: .
            dockerfile: Dockerfile.prod
        # サービス起動後に入力されるコマンドを設定
        command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
        # データを永続化させる場合の設定
        volumes:
            - static_volume:/usr/src/app/static
        # 開放するポートを指定。`host:container`
        expose:
            - 8000
        # 環境変数を指定
        env_file: .env
        # 接続するサービスを指定(対象のコンテナとリンク)
        depends_on:
            - postgres

    postgres:
        image: postgres:11.4-alpine
        # データベースの永続化
        # ホストのディレクトリにマウントしない様に、先頭に`./`をつけない
        volumes:
            - postgres_data:/var/lib/postgresql/data
        # su権限を持つ、指定されたユーザーと同じ名前のデータベースを作成
        # valueはdjangoサービスで指定したものと同じに
        env_file: .env.db

    nginx:
        build: ./nginx
        volumes:
            - static_volume:/usr/src/app/static
        ports:
            - 1337:80
        depends_on:
            - django

# トップレベルに書く「名前付きvolumes」は複数サービスから参照できる
volumes:
    postgres_data:
    static_volume:

